### ISSUE TITLE
Configure HTTP(S) proxy for importers and scrapers

### ISSUE THREAD

**Issue by evolution536** [docintelapp/DocIntel#13]
Is there an option in the deployment to configure a HTTP(S) proxy for the scrapers and importers? RSS import now fails because it doesn't use the proxy. I could not find such an option in config/appsettings.json and it is unclear to me whether the application picks environment variables or not.

Thanks in advance!

**Comment by ancailliau** [comment]
The proxy should have been ignored from the begining :-) Thanks for the report.

I also wrote a preview documentation for that specific issue that is available on https://docs.docintel.org/docs/admin/importers/ (SSL certificate and DNS record might not be up-to-date yet)

There were also additional bugs in the code. Fixes will be pushed with the next release on Nov 17.
