### ISSUE TITLE
Error while initial deployment of the `SolR` service

### ISSUE THREAD

**Issue by silvian-io** [docintelapp/DocIntel#2]
While running
```
docker run --name docintel-dev-solr \
  -v $datafolder/solr/:/var/solr \
  -d solr
```
the docker container fails with:
```
Cannot write to /var/solr as 8983:8983
drwxr-xr-x 2 root root 4096 Oct 18 08:13 /var/solr
```
Ran both root and non root.

**Comment by johnk3r** [comment]
I have the same problem.

**Comment by ancailliau** [comment]
Yes, indeed. Thanks for the report. I'm looking into a fix!

In the meantime, you can always chmod and chown the folders.

**Comment by d4ms3c** [comment]
You need to set right permission: sudo chown 8983:8983 ./data/solr
Then you must delete docintel-dev-solr container and run again "run.sh".

It works for me!

**Comment by ancailliau** [comment]
Yes, exactly. I'm no expert in docker but docker will mount the volume while respecting the permission of the host.

**Comment by Droogy** [comment]
Now I'm getting a different error, 

"Core 'document' already exists!"
![image](https://user-images.githubusercontent.com/63867669/196603383-7f0c1175-aa6a-4cb3-b1f2-dae2f1829a4e.png)

**Comment by AntoninHL** [comment]
Hi

Same here...
Core document already exists...

```
📚 Configuring SolR
32645a692c6b19e85148924007a9b2e6b57bee047b7c9c9ad24b47a245d69b29
Wait for SolR to be up-and-running
WARNING: Using _default configset with data driven schema functionality. NOT RECOMMENDED for production use.
         To turn off: bin/solr config -c document -p 8983 -action set-user-property -property update.autoCreateFields -value false

ERROR: 
Core 'document' already exists!
Checked core existence using Core API command:
http://localhost:8983/solr/admin/cores?action=STATUS&core=document
```

And nothing listening on port 5005...

**Comment by shannaniggans** [comment]
you could try commenting out the line in run.sh - "docker exec -it docintel-dev-solr solr create_core -c document" ?
