### ISSUE TITLE
How to enable DTD?

### ISSUE THREAD

**Issue by xme** [docintelapp/DocIntel#21]
While fetching a RSS feed, I got this:

`docintel-dev-importer           | 2022-11-11 07:14:10.2863 [ERROR] [DocIntel.Services.Importer.Runner] For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.
`

Is there a way to enable this? Alternative?

**Comment by ancailliau** [comment]
Documentation has been added for the new settings: https://docs.docintel.org/docs/admin/security.html#dtd-processing
