### ISSUE TITLE
Mismatch between sources and web interface

### ISSUE THREAD

**Issue by xme** [docintelapp/DocIntel#22]
I checked in the DB for my sources. I've 8 rows.
When I browse to "Sources" -> "View all", I don't see the same amount and a deleted source is still displayed (while NOT in the db!?)
Is there some caching mechanism in place somewhere?

**Comment by ancailliau** [comment]
There might be some delay (up to 15 minutes) for the search index to commit the latest changes. On large instance, the impact of writing the index at every operation is too high. I should add a configuration for that.

**Comment by ancailliau** [comment]
This is now documented at https://docs.docintel.org/docs/admin/delays.html
