### ISSUE TITLE
Wrong number of documents displayed in Sources listing

### ISSUE THREAD

**Issue by xme** [docintelapp/DocIntel#26]
While browsing my sources, the number of documents related to them is always "0" (next to the reliability indicator)
(when I click on resources, they are documents)

**Comment by ancailliau** [comment]
I documented why some numbers might appear incorrect in real-time, or why the index might not be as up-to-date as expected. See https://docs.docintel.org/docs/admin/delays.html

These are all production tradeoffs that will depend on your environment. 

Next version will allow for custom delays.
