### ISSUE TITLE
"Page cannot be found" when attempting to delete a tag

### ISSUE THREAD

**Issue by shannaniggans** [docintelapp/DocIntel#30]
"Page cannot be found" when attempting to delete a tag.
Tag has been used to tag entries so maybe that's why?

![image](https://user-images.githubusercontent.com/5997121/202088520-b1de001f-68c7-4998-9afb-fc04ab796097.png)

Nothing in the webserver logs but i can check on other containers if there is somewhere else to check for logs?

If i edit all the documents that had this tagged, then i get confirmation to delete.

![image](https://user-images.githubusercontent.com/5997121/202088911-5c08c446-3f71-46f9-bb9b-0bcec7fe29be.png)
![image](https://user-images.githubusercontent.com/5997121/202089024-7df6abf2-e0b8-4e72-81d5-f2b7d303458e.png)

So works as expected if there are no current tags, but should probably display an error rather than page not found :)

**Comment by ancailliau** [comment]
Fixed in the upcoming version.
