### ISSUE TITLE
Error while initial deployment of the SolR service

### ISSUE THREAD

**Issue by AntoninHL** [docintelapp/DocIntel#5]

**Comment by AntoninHL** [comment]
Hi

Same problem as described in issue #2 
Core document already exists...

```
📚 Configuring SolR
32645a692c6b19e85148924007a9b2e6b57bee047b7c9c9ad24b47a245d69b29
Wait for SolR to be up-and-running
WARNING: Using _default configset with data driven schema functionality. NOT RECOMMENDED for production use.
         To turn off: bin/solr config -c document -p 8983 -action set-user-property -property update.autoCreateFields -value false

ERROR: 
Core 'document' already exists!
Checked core existence using Core API command:
http://localhost:8983/solr/admin/cores?action=STATUS&core=document
```
And nothing listening on port 5005...

**Comment by shannaniggans** [comment]
you could try commenting out the line in run.sh - "docker exec -it docintel-dev-solr solr create_core -c document" ?

**Comment by ancailliau** [comment]
That specific error should have been avoided by the condition on line 96 of the run.sh. Can you confirm that you were using the latest version of the script?

**Comment by ancailliau** [comment]
You could add probes for the dependencies https://docs.docker.com/compose/startup-order/ However, this will be not be included in the default script, as it requires an additional dependency and is dependent on how you deploy the stack. For example, in Kubernetes, the setup would be different and would not requires that dependency. 

Launching the dependencies and wait for them to be up, then launch DocIntel solves the problem.
