### ISSUE TITLE
Filtering by tags not prefixed with facet in Search view

### ISSUE THREAD

**Issue by NORMA-MO** [docintelapp/DocIntel#53]
When viewing documents in Search view and selecting a tag under a facet for filtering, the facet is not included when the filter is applied. Resulting in no results for the filter.

![image](https://user-images.githubusercontent.com/114404102/221151539-7a8c87d5-5631-4349-a3b1-0610628c1f3f.png)

Note: Works for document metadata (Classification, Registered by, Source and Source Reliability)

**Comment by ancailliau** [comment]
Fixed with new filters. Changes to be pushed and docker images to be updated.
