### ISSUE TITLE
Adding an RSS Keyword to a source doesnt seem to save.

### ISSUE THREAD

**Issue by shannaniggans** [docintelapp/DocIntel#57]
Have tested by editing an existing source and also creating a new source.

1. RSS Keywords are added in the field under RSS Feed, 
2. Scrape RSS feed? is selected.
3. Save
4. Open the source and edit and the RSS Keyword field is empty.

**Comment by ancailliau** [comment]
The bug appears to be fixed with the work done with the recent refactoring.
