### ISSUE TITLE
Changing Admin Password

### ISSUE THREAD

**Issue by g33kroid** [docintelapp/DocIntel#59]
Hi Team 

I am trying to change the admin password of a fresh installation. 

From the Portal I click on the Avatar -> Change Password and I get Error 404 Page not found

![image](https://user-images.githubusercontent.com/16447622/231564372-58074b4f-2a48-44e6-878f-82219922a7bd.png)

Is there a way I can change the admin password from GUI or CLI. I tried to re-add the user with different password but it says User Exists 

Appreciate your Support.

**Comment by grolinet** [comment]
On the cli you can use this command to change the password of the admin user:
```
docker exec -it docintel-dev-webapp dotnet /cli/DocIntel.AdminConsole.dll user reset --username admin
```

Using the command:
```
docker exec -it docintel-dev-webapp   dotnet /cli/DocIntel.AdminConsole.dll
```
will also print the help information for all the stuff you can do with this tool.
```
USAGE:
    DocIntel.AdminConsole.dll [OPTIONS] <COMMAND>

OPTIONS:
    -h, --help       Prints help information   
    -v, --version    Prints version information

COMMANDS:
    user               
    role               
    classification     
    index              
    document           
    observable         
    whitelist          
    tags               
    thumbnails 
    ```

**Comment by ancailliau** [comment]
That's summed up :-) Many thanks @grolinet !
