### ISSUE TITLE
PDF 1.4 Document is crashing the tool

### ISSUE THREAD

**Issue by g33kroid** [docintelapp/DocIntel#72]
I am trying to upload a Threat report, but it keeps loading and the tool eventually crashes.  I am not sure if this version of PDF is not supported below how the documents looked like in the portal. 

![image](https://github.com/docintelapp/DocIntel/assets/16447622/fdb4276c-c49d-4faa-bf33-57083531835b)

and the original document 
![image](https://github.com/docintelapp/DocIntel/assets/16447622/f3e85a23-b20e-429b-996a-4e9d9f300139)

The document link
https://media.licdn.com/dms/document/media/D4E1FAQErw15rYKuIGw/feedshare-document-pdf-analyzed/0/1686591981935?e=1687996800&v=beta&t=HLnjLYY-HVq6XiiHgSn3DuD7vj4gBOU6QkAlznpM-wU

**Comment by NORMA-MO** [comment]
Same here from a fresh build last week, I get to the following log error:
`docintel-dev-webapp             | 2023-06-27 13:49:54.6366 [ERROR] [DocIntel.WebApp.Controllers.DocumentController] null`
